name: CI

on:
  push:
    branches:
      - main
      - release/**
      - stable
  pull_request:
    branches:
      - main
      - release/**
      - codex/**

jobs:
  build-linux-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        std: [11, 17]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Boost (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libboost-all-dev
      - name: Install Boost (macOS)
        if: runner.os == 'macOS'
        run: brew install boost
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${{ matrix.std }}
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        std: [11, 17]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Boost (Windows)
        shell: pwsh
        run: |
          choco install boost-msvc-14.3 -y --no-progress --prerelease
          $boost = Get-ChildItem -Path 'C:\local' -Filter 'boost_*' | Select-Object -First 1
          "BOOST_ROOT=$($boost.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "$($boost.FullName)\lib64-msvc-14.3" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${{ matrix.std }} -DCMAKE_CXX_FLAGS="/sdl /guard:cf"
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure

